version: '3.3'
services:
    redis:
        container_name: redis
        image: redis:7
        ports:
            - '127.0.0.1:6379:6379'
    captcha_service:
        container_name: captcha_service
        build: .
        environment:
            - PORT=3000
